# Site settings
title: Kontinu | Devops Guatemala

navbar_brand: Kontinu
images:
  logo: kontinu-badge-logo.png
  header_logo: kontinu-badge-logo.png

email: info@kontinu.io
url: "/"
description: "Kontinu - Devops Guatemala - Consultoria Devops en Guatemala, nos especializamos en: Cloud, Docker, SCRUM, Continuous Delivery, Continuous Integration"

skills: "Consultoria Devops y Bootcamps"
meta_author: Cano Marcos

# Google webmaster tools
google_verify: _R6q2LUK8VcUpkmxSdJQJGFfEb6RMjlVEIkDA8zpyc0


# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:



# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-111567273-1


## google optimize
go:
  # id:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# 1:
# salmon - azul - azulgris
# e49695  003366 263340
color:
  primary: 1E293B #374867 ; #3241E4; #FF7E79 #80B3FF
  primary-rgb: 30, 41, 59 # "255,242,241" #"128,179,255"
  secondary: 1E293B #FD6E8A
  secondary-dark: 243342 #A2122F
  accents: 59B392


about:
  column1: |+
    Somos una empresa con sede en la ciudad de Guatemala,
    formada por expertos en el tema, con años de experiencia en llevar a empresas a la adopción y transformación efectiva Devops,
    contamos con el personal certificado en Jenkins, Docker, AWS y Devops; que a la vez disfrutan el compartir sus experiencias
    y conocimiento.
    <br>
    Nos dedicamos a que nuestros clientes alcancen el siguiente nivel en la entrega de desarrollo de software.
    <br>
    Formamos, orientamos y a hacemos que nuestros clientes adopten todas las buenas practicas que los dirigirán hacia
    la transformación DevOps en su empresa.
  column2: |+
    Devops es la combinación de filosofías culturales, nuevas practicas
    y uso de herramientas entre equipos multi-funcionales que permiten incrementar
    la habilidad de la organización para la entrega de software a altas velocidades.
    <br>
    Logramos que nuestros clientes adopten Devops ofreciendo mulitples servicios:
    capacitaciones, talleres, pruebas de diagnóstico y entrenamiento del personal en tecnologías Devops
    para que nuestros clientes puedan cumplir con la alta demanda en el mercado
    y tengan una mejor ventaja competitiva en la industria de tecnología.




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  #- title: bitbucket
  #  url: http://gitlab.com/kontinu/home
  #- title: github
 # url: http://github.com/kontinu/home



# Postal address (add as many lines as necessary)
address:
  - line: 📧  info@kontinu.io
  - line: 📍  Guatemala City.
  - line: 📞  +(502) 30093002


# # Footer settings
# footer:
#   copyright: Kontinu
#   location: Ubicación
#   #social: En la Web
#   credits: Créditos
# # Credits content

footer:
  - line:
        title: servicios
        content:
            - devops
  # - line:
  #       title: column 2
  # - line:
  #       title: column 3


credits: 'Kontinu 2021'



# Build settings
#markdown: kramdown
#permalink: pretty



exclude:
  - .img-sources/
  - "*.sh"
  - docker-compose.yml
  - README.md
  - Gemfile*
  - .gitlab-ci.yml
  - LICENSE
  - experiments
  - .gitignore
  - .git
  - LICENSE


